[server]
host: 127.0.0.1
port: 17126
klippy_uds_address: /run/fre3nder-klipper/klippy.sock

[machine]
provider: none
validate_service: False
validate_config: False

[file_manager]
file_system_observer: none
check_klipper_config_path: False

[announcements]
enable_moonlight: False

[update_manager]
channel: stable
enable_system_updates: False

[authorization]
trusted_clients:
  127.0.0.1
  10.0.0.0/8
  172.16.0.0/12
  192.168.0.0/16
  ::1
  fc00::/7
  fe80::/10

[include fre3nder/*.conf]
